meower-media/server

requirements.txt

pip install -r requirements.txt

txt file for pip

---

meower.py

When a user deletes their own post it didn't return the status code, this commit fixes that.

Fix self post deletion

---

rest_api.py

Fixes an API vulnerability that allows anyone to downlod a post that they may not have access. This limits the API to only returning home posts.

Fix API post vulnerability

---

security.py

This patch fixes a vulnerability that allows `lower_username` to be changed from `update_config`, this will allow duplicate accounts if it isn't fixed.

URGENT PATCH - lower_username vulnerability

---

meower.py

Add "all_chats" to "get_chat_list" to make it easier to get a chat's data without having to run a seperate command.

Add "all_chats" to "get_chat_list"

---

files.py
meower.py

Small update to automated inbox message content, account termination, group chat sates and auto-added supported versions.

Beta 5 Release 6

---

supporter.py

This helps with the not being authenticated properly bug, just adds a small delay between kicking a currently logged in client and allow the new user to get an AutoID.

Fix not being authenticated properly

---

meower.py

Kind of urgent | User's not being able to leave group chats

---

meower.py

made on gh web gui
fixes  #100 
You need to manualy kick duplicates out

fixed adding someone to a groupchat twice

---

meower.py

Make group chat names censored

---

better_profanity/contaning_allowed.txt
better_profanity/profanity_wordlist.txt

add whitelist words.

---

rest_api.py

Only allow authorized users to get posts from home beyond the first page.

Only alow first page of home when unauthorized

---

better_profanity/contaning_allowed.txt

Adds `japanese` as a whitelisted word in better_profanity

Add `japanese` into better_profanity whitelist

---

better_profanity/profanity_wordlist.txt

there were some words that i don't think should *really* be filtered. (like stfu can be interpreted as frick, and for some reason fat/fatass was filtered.)

update profanity list

---

better_profanity/profanity_wordlist.txt

Reverts meower-media-co/Meower-Server#137
Revert because there are a few words that SHOULD BE blocked.

Revert "update profanity list"

---

meower.py

So EASY TO FIX

---

main.py
meower.py
supporter.py

Limit adding/removing members to 5 members per 3 seconds, and limit group chats to 100 members.

Add limits to group chats

---

meower.py

check old password when using change_pswd and change max password length to 255 characters

check old password when using change_pswd

---

cloudlink.py
meower.py

Remove size limits on messages

---

.gitignore
cloudlink.py
rest_api.py
websocket_server/.gitignore
websocket_server/LICENSE
websocket_server/README.md
websocket_server/__init__.py
websocket_server/client.html
websocket_server/releases.txt
websocket_server/requirements.txt
websocket_server/server.py
websocket_server/tests/conftest.py
websocket_server/tests/test_handshake.py
websocket_server/tests/test_message_lengths.py
websocket_server/tests/test_server.py
websocket_server/tests/test_text_messages.py
websocket_server/thread.py
websocket_server/websocket_server.py

Fix ip bug

---

README.md

I did it tnix

---

README.md

Use `--recursive` flag for `git clone` instead of using `git submodules init && git submodules update` after cloning

---

main.py
meower.py
rest_api/__init__.py
rest_api/admin.py
rest_api/me.py
security.py

* Remove ToS versions (this will be moved to the auth server)
* add the ability to get report history
* Add auth check on report history endpoint
* fix content_id on post reports

Add endpoint to fetch report history (#207)

---

.env.example
database.py
requirements.txt
rest_api/me.py
security.py
supporter.py

* feat: Add the ability for users to request a data export
* fix: add a database index for `user` field in data_exports collection
---------

Add the ability for users to request a data export (#221)

---

database.py
rest_api/chats.py
rest_api/posts.py
supporter.py

Git did not include posts.py initially

Feat: Chat Pinning

---

database.py
rest_api/admin.py
security.py

New Perm is CHANGE_PROFANITY (524288)

Feat: API for adding/removing whitelist/blacklisted words 

---

cloudlink.py
rest_api/__init__.py

^
This was originally intended to combat the anti-bridge (but thankfully that situation has come to a close?) but now serves as an application-level security feature to block malicious clients.

Implement origin blocker

---

cloudlink.py
rest_api/__init__.py
rest_api/auth.py
rest_api/posts.py
rest_api/uploads.py
rest_api/users.py

this adds the following endpoints:
- /auth/register (gen_account in cl)
- /auth/login (authpswd)
- /posts/post-id/report (report)
- /users/username/report (report)

api account creation and message reporting

---

cloudlink.py
database.py
dockerfile
requirements.txt
rest_api/admin.py
rest_api/chats.py
rest_api/home.py
rest_api/inbox.py
rest_api/me.py
rest_api/posts.py
rest_api/search.py
rest_api/users.py
supporter.py

This PR was made to be able to make some final changes using a branch within this repo before merging, please see #245 for more details.

Post reactions (replacement to #245)

---

database.py
rest_api/home.py
rest_api/posts.py
supporter.py

Post replies

---

rest_api/v0/chats.py

fix not being able to toggle allow_pinning on chats

---

rest_api/v0/home.py

fix: limit home to first page when unauthed

---

SECURITY.md

The link is broken, same deal as the other pull requests.

Update SECURITY.md to fix link
